[[redirects]]
  from = "/torrents/*"
  to = "https://torrentsfreelancer.herokuapp.com/torrents"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
